language: python

python:
    - "2.7_with_system_site_packages"
    - "2.6"

branches:
    only:
        - master

sudo: false

install:
    - pip install -r requirements-travis.txt

script:
    - inspekt lint
    - inspekt indent
    - inspekt style
